### ISSUE TITLE
Examples/limitations on burst-target="{xpath}" in sch:rule burst-mode="copy-of|snapshot" burst-target="{xpath}" context="book"?

### ISSUE THREAD

**Issue by martin-honnen** [HiltonRoscoe/streamable-schematron#1]
Based on the previous interchange of ideas on Slack I think I understand your proposal, with the exception of the optional `burst-target="{xpath}"` attribute that it shows for `sch:rule`. What would be examples on that? What kind of limitations would the path have? Have you designed/prototyped that to an XSLT template/if compilation?

**Comment by JDziurlaj** [comment]
My thought was that you might have a `sch:rule` `context` that matches an particular node, but you aren't actually interested in all of the content, just a particular child node, so this would avoid copying the whole thing in. Now I realize that you could put that in the context itself, e.g.

```
<sch:rule context="matchItem[@matchAttr = 1]/usefulData" />
```

I will remove this from the spec.
